<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User GroupsAll Groups</name>
   <tag></tag>
   <elementGuidId>7eccf1cb-2f29-4976-b8cc-f38e9b3a49f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toolbar-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;User GroupsAll Groups&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b45db7a-2050-469c-8400-1b4fa86fab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toolbar-left</value>
      <webElementGuid>ce78343f-1f8c-41bf-ae93-92db1c0bf91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User GroupsAll Groups</value>
      <webElementGuid>a0eab2cd-53ac-48d1-afec-e5ccc515c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-root MuiBox-root css-0&quot;]/main[@class=&quot;main-content MuiBox-root css-19toco3&quot;]/div[@class=&quot;split-dashboard-page&quot;]/div[@class=&quot;dashboard-toolbar&quot;]/div[@class=&quot;toolbar-left&quot;]</value>
      <webElementGuid>eb28d3b5-e220-44a3-b70e-341e80133416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div</value>
      <webElementGuid>d5bd849f-0164-4fe9-885f-e615f3667d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch to Old UI'])[1]/following::div[4]</value>
      <webElementGuid>f1267018-b995-434f-9343-80d42336b997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISENGAGEMENT'])[1]/following::div[6]</value>
      <webElementGuid>2c9f1bf7-ca71-48de-9686-766fd4e12f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div</value>
      <webElementGuid>4fb2c200-6480-46b0-ac62-d918e6682db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'User GroupsAll Groups' or . = 'User GroupsAll Groups')]</value>
      <webElementGuid>ff5dcdf2-f36b-43b8-be08-854a350faf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
