<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1224</name>
   <tag></tag>
   <elementGuidId>4dbf70e3-5a38-4439-8cb1-07759efff454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.split-subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;12/24&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5b232f6-0275-489b-93fd-5bc7db72adad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>split-subtitle</value>
      <webElementGuid>b468db2e-8c3a-4572-9d46-adb35f12eb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12/24</value>
      <webElementGuid>0848e2f1-f859-4ac9-8edb-eba8d814c13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-root MuiBox-root css-0&quot;]/main[@class=&quot;main-content MuiBox-root css-19toco3&quot;]/div[@class=&quot;split-dashboard-page&quot;]/div[@class=&quot;split-dashboard-container&quot;]/div[@class=&quot;split-dashboard-grid&quot;]/div[@class=&quot;ant-row split-dashboard-row css-mncuj7&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-md-6 ant-col-lg-5 css-mncuj7&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation3 split-dashboard-card-1 widget4-container css-110i50s&quot;]/div[@class=&quot;split-chart-title&quot;]/div[1]/div[1]/div[@class=&quot;split-subtitle&quot;]</value>
      <webElementGuid>a566d66a-a56d-49fc-a3fa-8dd078c2d498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>8566dbdf-4f36-4510-b2d4-522f5d26260b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retention Risk'])[1]/following::div[1]</value>
      <webElementGuid>e41d1a2e-9bdb-4ce1-93af-b3b1a69ada49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Teams'])[1]/following::div[9]</value>
      <webElementGuid>e2660379-cf8c-4aa7-b562-221b976e2301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='↓'])[1]/preceding::div[5]</value>
      <webElementGuid>20631ed6-c809-4a91-92c6-8ad3a028d7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At Risk'])[1]/preceding::div[6]</value>
      <webElementGuid>c79065a3-42d1-4885-8ca9-5367e71fd583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12/24']/parent::*</value>
      <webElementGuid>87128227-ebc6-4356-9937-374cf94863b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>5d163181-5f02-4dd5-955f-d9748b99e4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '12/24' or . = '12/24')]</value>
      <webElementGuid>44141a5e-cf15-42d4-a6aa-3f0251b9ca55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
