<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10</name>
   <tag></tag>
   <elementGuidId>2229f887-74e8-45af-a7dd-dfada1acdf5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/main/div/div/div/div/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-select.ant-select-outlined.css-os2fvf.ant-select-single.ant-select-show-arrow.ant-select-open > div.ant-select-selector > span.ant-select-selection-wrap > span.ant-select-selection-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>672da819-31c0-4cdf-8d1e-3ee5e70dbe52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>00999e8e-db1f-4c23-85d3-3b55f3f74357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7fcf24c9-fe1f-4290-bae4-c17b1d31587c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>37480ce1-0f2b-47e7-aff2-35fdda4864fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-root MuiBox-root css-0&quot;]/main[@class=&quot;main-content MuiBox-root css-19toco3&quot;]/div[@class=&quot;drilldown-container&quot;]/main[@class=&quot;main-drill&quot;]/div[@class=&quot;drilldown-toolbar&quot;]/div[@class=&quot;toolbar-left&quot;]/div[@class=&quot;ant-select ant-select-outlined css-os2fvf ant-select-single ant-select-show-arrow ant-select-open&quot;]/div[@class=&quot;ant-select-selector&quot;]/span[@class=&quot;ant-select-selection-wrap&quot;]/span[@class=&quot;ant-select-selection-item&quot;]</value>
      <webElementGuid>9a6ccc27-e7f8-45e2-9132-77ea7f260584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/main/div/div/div/div/span/span[2]</value>
      <webElementGuid>39426799-830f-4a10-b4e4-3bfdd9ba4294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records to display:'])[1]/following::span[3]</value>
      <webElementGuid>1d865ac8-5a1a-4f62-9311-3ed7cb2db9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fetch'])[1]/following::span[4]</value>
      <webElementGuid>71d25320-ba56-4590-a03b-ac3e0eebb9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::span[13]</value>
      <webElementGuid>ea334783-4027-4f59-9aae-ceacc3858a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>49e8e03a-235f-4d9d-a30b-ee67625fa690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/span/span[2]</value>
      <webElementGuid>c7f0d4b1-18f2-40c0-a9a4-7730bff0f645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '10' and (text() = '10' or . = '10')]</value>
      <webElementGuid>3f7bc763-be7d-4a98-8860-4893ebbb6119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
