<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Disengagement_apexcharts-radialbar-hollow</name>
   <tag></tag>
   <elementGuidId>504bb331-3815-44fd-846b-1666ac54f964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle.apexcharts-radialbar-hollow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apexchartsp5hq7lku circle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>21815c2f-f67e-47ac-9587-e2c15ffcd2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>30.168597560975613</value>
      <webElementGuid>6000ee27-535e-47f8-833c-9d976321de1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>47.5</value>
      <webElementGuid>e8d1ca25-fa7c-4174-9969-469208dc9705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>47.5</value>
      <webElementGuid>00e1341c-0612-4b53-87e7-88664f799c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-radialbar-hollow</value>
      <webElementGuid>9aecedf7-c60f-467e-bf5a-68f4b26e5fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>ce09c948-aff4-47be-bb03-d18d7c0e04a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apexchartsp5hq7lku&quot;)/svg[@class=&quot;apexcharts-svg&quot;]/g[@class=&quot;apexcharts-inner apexcharts-graphical&quot;]/g[@class=&quot;apexcharts-radialbar&quot;]/g[1]/g[2]/circle[@class=&quot;apexcharts-radialbar-hollow&quot;]</value>
      <webElementGuid>60cf1296-51c1-41c3-81bd-fa760bd1a0af</webElementGuid>
   </webElementProperties>
</WebElementEntity>
