<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_High</name>
   <tag></tag>
   <elementGuidId>9109b48b-79fb-40c9-a5f1-46e2643c98b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.radial-label-tooltip.ant-tooltip-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div[2]/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#root >> internal:text=&quot;High&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15a24a08-2b70-41b1-861d-ab31c6ce95bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radial-label-tooltip ant-tooltip-open</value>
      <webElementGuid>2f3eabf8-d9e1-4d5f-b74c-a54cfca9d894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>«ra1»</value>
      <webElementGuid>30c3364c-20bc-4089-9cb5-0bc42bfcc653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>High</value>
      <webElementGuid>b5dba5de-d3aa-4687-9b85-78584d16a9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-root MuiBox-root css-0&quot;]/main[@class=&quot;main-content MuiBox-root css-19toco3&quot;]/div[@class=&quot;split-dashboard-page&quot;]/div[@class=&quot;split-dashboard-container&quot;]/div[@class=&quot;split-dashboard-grid&quot;]/div[@class=&quot;ant-row split-dashboard-row css-os2fvf&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-md-8 ant-col-lg-8 css-os2fvf&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation3 split-dashboard-card-1 css-110i50s&quot;]/div[@class=&quot;split-card-content radialChartDis&quot;]/div[@class=&quot;split-radial-chart split-radial-container&quot;]/div[@class=&quot;radialchartcontainer&quot;]/div[@class=&quot;radial-label-tooltip ant-tooltip-open&quot;]</value>
      <webElementGuid>e6c463ce-d259-474f-90ae-4bf2e70556f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>eeb79792-6574-4168-91b8-a4c4867a34f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='↓'])[1]/following::div[1]</value>
      <webElementGuid>55180bfa-bdcc-459a-92b9-8f66b48b0bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disengagement'])[1]/following::div[10]</value>
      <webElementGuid>6d3df294-1e78-4f8a-8ee5-47c1e6c62e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='↓'])[2]/preceding::div[4]</value>
      <webElementGuid>6d42aa56-100d-4637-9518-de5b1aff7b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/preceding::div[5]</value>
      <webElementGuid>fb53ec43-0d44-4e77-91af-31f246d1858b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='High']/parent::*</value>
      <webElementGuid>ab0494cc-fafa-47b0-b91b-da60c40ac85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>7fc3cabd-2fce-4a73-94fe-2f2cfae69a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'High' or . = 'High')]</value>
      <webElementGuid>a57e1f4f-560e-4a17-9bf2-eb7fe453845a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
