<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WORKFLOW</name>
   <tag></tag>
   <elementGuidId>3082c29d-310c-4d1f-84ba-133fd92e6a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wfmForIPAD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wfmForIPAD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;WORKFLOW&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73fbb015-986d-4504-bb15-6b212c69b771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b1183b69-f6a1-440f-a2fa-461beb169dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle padding-Left-10px</value>
      <webElementGuid>3e9d15c2-1a8f-4c82-89cc-8590b45a72ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wfmForIPAD</value>
      <webElementGuid>b3730a5f-8f1e-46d2-b00d-cfbb242fff85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>c8ef7457-914a-4e30-b1c4-12e541fb72a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												WORKFLOW
											</value>
      <webElementGuid>e91566a0-b91e-4597-8b8b-b25bc6ae7ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wfmForIPAD&quot;)</value>
      <webElementGuid>2a507bea-f95d-4d3c-9269-3d4fc2e90ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wfmForIPAD']</value>
      <webElementGuid>0f6cd2ba-24dc-4218-9b48-79fe5b8d73e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='leftMenus']/li[5]/a</value>
      <webElementGuid>4f4f365a-b74e-4c99-9f8b-29f50e609439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WORKFLOW')]</value>
      <webElementGuid>daa8ec42-9274-4779-9a75-f8a1a2817937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROJECTS'])[1]/following::a[1]</value>
      <webElementGuid>31d6dd37-62da-413e-9e85-3f130a088d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET OPTIMIZATION'])[1]/following::a[2]</value>
      <webElementGuid>78c805b9-4ac5-4ed4-ba84-41bfbc57aa73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADVANCED ANALYTICS'])[1]/preceding::a[1]</value>
      <webElementGuid>143fbc87-2e30-410e-9a29-5ff522a7bd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MORE'])[1]/preceding::a[2]</value>
      <webElementGuid>4827f558-db48-4f9f-9092-a6534d4571e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WORKFLOW']/parent::*</value>
      <webElementGuid>0f667895-1752-4a07-8f98-88f45d9af6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[13]</value>
      <webElementGuid>9e0b8a00-2160-43f4-94b5-ff01ebc199ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>a9f9cef4-f7b4-4726-ade7-a26e84e43fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'wfmForIPAD' and (text() = '
												WORKFLOW
											' or . = '
												WORKFLOW
											')]</value>
      <webElementGuid>0e7ae769-f4ce-432c-b742-49c547f375f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
