<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Captcha Text_loginSubmitFrm</name>
   <tag></tag>
   <elementGuidId>bfa09484-01ed-47eb-b351-542c1f7b110a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginSubmitFrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginSubmitFrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loginSubmitFrm</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aee7bad0-99b3-4768-9374-bce4536deda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-submit submitloginform</value>
      <webElementGuid>d4e5cc69-ebd3-4eb5-ac78-832ec1590404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginSubmitFrm</value>
      <webElementGuid>9a1b9414-d348-4e56-b195-be774c1f001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginSubmitFrm&quot;)</value>
      <webElementGuid>3121720c-ba49-4b50-afa6-37fc0cc1faa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loginSubmitFrm']</value>
      <webElementGuid>1a32a281-c28b-4c2a-a987-b359ea930a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AuthenticationForm']/div[2]</value>
      <webElementGuid>970ab7ec-0e8f-43f6-8b3a-db463109f9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captcha Text'])[1]/following::div[3]</value>
      <webElementGuid>b0cb7e3a-9624-482b-a518-e55bd406ca83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Id'])[1]/following::div[6]</value>
      <webElementGuid>d591657a-63cf-4abf-900e-7f71fe0f7c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© JaMocha Tech Pvt. Ltd. 2009-2026'])[1]/preceding::div[5]</value>
      <webElementGuid>498a50de-1691-42c7-b78c-843a90180472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProHance v9.9.10.153'])[1]/preceding::div[6]</value>
      <webElementGuid>dbae1deb-7380-445f-8c1f-1f28a3c1fd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>8a67f2d9-52f1-4c18-b255-836d3a94b428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loginSubmitFrm']</value>
      <webElementGuid>84325da1-a7a7-4257-b037-4f971e8beca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
