<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Workflow Settings_contentFrame</name>
   <tag></tag>
   <elementGuidId>61b22ae3-739c-40b4-861c-2c55d2cad07f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7d341902-aa2a-4562-bcd3-cc010774e131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>909305dc-40ff-43ad-a009-3b1869977e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>37868185-08e4-4a8b-8b75-a394e42bbb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85639f4c-7bb0-41db-806d-7fa96a19c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/phworkflow/WorkflowExDashboard/layout.htm?menuItemId=233</value>
      <webElementGuid>db2b8110-7279-4950-97ce-683b8ab10571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFrame&quot;)</value>
      <webElementGuid>ac99054b-4c94-43a5-9d43-a5d5fdaf9a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentFrame']</value>
      <webElementGuid>7035421d-ef72-4a8b-ac21-055ddd6bfab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContentDiv']/iframe</value>
      <webElementGuid>9af26114-6561-45c2-b656-453df6dd6827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5ab8cd40-c81e-4aac-90e8-0b0413aef8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame' and @name = 'contentFrame' and @src = '/phworkflow/WorkflowExDashboard/layout.htm?menuItemId=233']</value>
      <webElementGuid>a83f589f-a395-45d0-adc1-c1efab85e817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
