<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retain container specific period_btn _26f434</name>
   <tag></tag>
   <elementGuidId>b57260c1-302f-4917-9055-bdcf5f5e8e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-dialog.ph-wf-width-430px-top-30px > div.modal-content > div.modal-footer.modal-footer-custom > div.col-lg-12.col-md-12.col-sm-12.ph-wf-text-align-center.ph-wf-padding-right-0px > span:nth-of-type(2) > input.btn.btn-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SAVE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SAVE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c28c088c-1f6a-43e6-ac50-b3b23e88e644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>11861750-7e79-479b-bcc6-232511367bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save</value>
      <webElementGuid>109059b9-7cd8-45be-9a20-cb97351227cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>74df2b0e-d0f4-40a4-8aae-16ca320aff50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnSaveContainerPrefOnClick</value>
      <webElementGuid>76a56310-1bb6-4c50-ab5f-bc6791ae5349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabCreationModal&quot;)/div[@class=&quot;modal-dialog ph-wf-width-430px-top-30px&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer modal-footer-custom&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 ph-wf-text-align-center ph-wf-padding-right-0px&quot;]/span[2]/input[@class=&quot;btn btn-save&quot;]</value>
      <webElementGuid>ac0761d4-c8b2-4310-acb2-7147d3da1b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SAVE']</value>
      <webElementGuid>3d8bc269-9968-4d86-9b7a-49a5605820aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabCreationModal']/div/div/div[5]/div/span[2]/input</value>
      <webElementGuid>2273faad-3a02-42fd-b996-7bbb98b8f819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span[2]/input</value>
      <webElementGuid>89006ff9-6039-4ebc-9f05-5be76fd614f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>a11ee499-2037-43a5-874d-20af99e9aa42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
