<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-_cell-1-undefined</name>
   <tag></tag>
   <elementGuidId>b15dcc03-eb71-4d8a-a8f9-8a995ed07304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[name()='svg' and @class=&quot;MuiSvgIcon-root MuiSvgIcon-fontSizeSmall css-vh810p&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#row-1 > #cell-1-undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd9117ef-ef34-47cd-9389-26a8f9d34340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-1-undefined</value>
      <webElementGuid>22b31714-d6f5-453b-839f-0c67a783cbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>83fcadd4-7921-4024-abd6-caca3c4a8657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>9f0eccce-b0c6-4628-8552-016069d1a67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ggWZvA sc-dTvVRJ sc-jwTyAe kitFYk efQMeo iOgaEC rdt_TableCell</value>
      <webElementGuid>f2684b4f-c445-4f88-8b07-1ed8c40bdd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>54dd0018-8045-4053-8523-06c3bdb4d04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>5%</value>
      <webElementGuid>92e6e044-97fc-4ec5-9206-cbeb0e09bcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-1&quot;)/div[@id=&quot;cell-1-undefined&quot;]</value>
      <webElementGuid>ef8fb24a-d673-4654-9711-095be50f0367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='cell-1-undefined'])[2]</value>
      <webElementGuid>50e4f3b0-f4d1-4dbd-a830-dfeaad772bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-1']/div</value>
      <webElementGuid>f8fbb54d-2a53-46b8-8620-f7c8fcbba1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::div[4]</value>
      <webElementGuid>3a363914-a011-4cba-80c2-daacfe69c602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RI'])[1]/following::div[6]</value>
      <webElementGuid>eec23021-141a-467b-acce-04758d48e64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PH Services (Tech Team)'])[1]/preceding::div[2]</value>
      <webElementGuid>58552297-4394-4373-8217-024580733ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHTECH'])[1]/preceding::div[4]</value>
      <webElementGuid>a363d272-e11a-4813-af06-1fdb55684039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>0c9e157a-3f80-4e1c-af8c-4ecb2e1aace4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-1-undefined']</value>
      <webElementGuid>0475fc1d-f1a5-44b1-ad02-0375a058bca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
