<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_delete</name>
   <tag></tag>
   <elementGuidId>abd33e7b-03de-48a3-9398-75f1d7d585b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id=&quot;categoryTable&quot;]/tr[4]/td[1]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;close&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>219b0ad1-2844-46ea-a8c1-a3ea3ab076dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>ebe12125-9ce4-47dd-91a8-350d47d9fb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>50660237-b5b3-4dbe-8447-9765725ae52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>3ff0613e-0de4-4a3b-8ba7-b304a75d6975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>2fa46744-84b2-45bf-af0c-fd68dfd0d4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogsuccessspan&quot;)/span[@class=&quot;alert alert-success config-alert&quot;]/a[@class=&quot;close&quot;]</value>
      <webElementGuid>7c4550f0-ed68-43f1-8ade-6b97d2018d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WorkLoad/Page_ProHance/iframe_Hierarchy Mapping_contentFrame</value>
      <webElementGuid>313bbab3-37c4-4a94-8629-a76d6c8d7eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//tbody[@id=&quot;categoryTable&quot;]/tr[4]/td[1]/a[1]</value>
      <webElementGuid>3fd76e4c-6950-456d-b396-8aad882f8c85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
