<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Hierarchy Mapping_contentFrame</name>
   <tag></tag>
   <elementGuidId>012920c3-e1da-4943-a3c5-0dc1c3f02cd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9e7bcb25-e1e1-48a5-8a66-c6a9984dc3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>bcbc3994-ae4d-4fcd-a77f-98b50f5636f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>0c851cff-bfe8-45c9-a8a7-e401869083c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>319146a7-d759-4424-b16a-9720d5e27343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prohance/WorkLoadCategories.htm?menuItemId=121</value>
      <webElementGuid>42e31efa-482d-42b3-80d8-4fde5506c978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFrame&quot;)</value>
      <webElementGuid>1992b761-b576-4886-b611-a3e80e2beec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentFrame']</value>
      <webElementGuid>fdb8dc14-a32b-45a4-a04f-5d0e17311029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContentDiv']/iframe</value>
      <webElementGuid>215ad2a9-a7d9-484b-b844-1da57f11b448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cff963fe-73aa-45eb-83d3-339af0b54f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame' and @name = 'contentFrame' and @src = '/prohance/WorkLoadCategories.htm?menuItemId=121']</value>
      <webElementGuid>ddeb7878-01bd-435e-a591-eb6466a76f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
