<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Workload Category test added successfully</name>
   <tag></tag>
   <elementGuidId>62a10aca-bf11-4ab8-95f3-b02856a9e671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='successmsgdiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#successmsgdiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Workload Category: test added successfully&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>324aca26-2552-4bf1-85d1-05a971f0c32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>successmsgdiv</value>
      <webElementGuid>ec53d953-e6f5-4d70-9c6c-21e071606e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workload Category: test added successfully</value>
      <webElementGuid>e963a126-17b7-43f8-bcc5-668e1fc13438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;successmsgdiv&quot;)</value>
      <webElementGuid>43d4e6a2-d78d-480b-a32a-e13f1886310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WorkLoad/Page_ProHance/iframe_Hierarchy Mapping_contentFrame</value>
      <webElementGuid>31075fd3-3231-4396-a776-15289b14ab41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='successmsgdiv']</value>
      <webElementGuid>e765ac1b-d149-4ddb-9e37-2aaafd397db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dialogsuccessspan']/span/span</value>
      <webElementGuid>8e825757-ff5b-48e3-80ac-9c96b1ec146a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::span[1]</value>
      <webElementGuid>34612a77-a9ca-4527-b0db-80d497633112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/preceding::span[2]</value>
      <webElementGuid>95c2c7a4-b58d-4146-bc52-7a5800f42d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/preceding::span[2]</value>
      <webElementGuid>c2fd10ab-faed-4dec-b25b-95d7f860e2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Workload Category: test added successfully']/parent::*</value>
      <webElementGuid>eb78f877-e99b-43d4-badc-8fed750fa94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>e21bac46-dbfb-4200-85ec-76abe1544438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'successmsgdiv' and (text() = 'Workload Category: test added successfully' or . = 'Workload Category: test added successfully')]</value>
      <webElementGuid>4ef84009-e201-4129-aaf0-8db3a6deced0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
