<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Medium</name>
   <tag></tag>
   <elementGuidId>e87344c6-df9c-4546-9327-f6029fc04e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.radial-label-tooltip.ant-tooltip-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#root >> internal:text=&quot;Medium&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9b97533-dd94-42d9-90fb-d588904a1a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radial-label-tooltip ant-tooltip-open</value>
      <webElementGuid>df55875f-ef31-4aa9-9f70-cf993aa22eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>«r15»</value>
      <webElementGuid>01cc6784-faee-4336-a4d2-8ffd233ee594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medium</value>
      <webElementGuid>dd48bce9-162f-4057-a4f6-02abbca24379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-root MuiBox-root css-0&quot;]/main[@class=&quot;main-content MuiBox-root css-19toco3&quot;]/div[@class=&quot;split-dashboard-page&quot;]/div[@class=&quot;split-dashboard-container&quot;]/div[@class=&quot;split-dashboard-grid&quot;]/div[@class=&quot;ant-row split-dashboard-row css-os2fvf&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-md-8 ant-col-lg-8 css-os2fvf&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation3 split-dashboard-card-1 css-110i50s&quot;]/div[@class=&quot;split-card-content radialChartDis&quot;]/div[@class=&quot;split-radial-chart split-radial-container&quot;]/div[@class=&quot;radialchartcontainer&quot;]/div[@class=&quot;radial-label-tooltip ant-tooltip-open&quot;]</value>
      <webElementGuid>f3dee682-6c12-4a99-96da-dd342398f92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>3238b8a7-4b40-4402-af81-b2d276324e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='↓'])[2]/following::div[1]</value>
      <webElementGuid>e5875a39-8bfc-4242-8a99-22bc265a4f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[1]/following::div[7]</value>
      <webElementGuid>32277e4c-1095-4602-8cd7-73dec88c0ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='↑'])[1]/preceding::div[4]</value>
      <webElementGuid>b3190f14-c847-4a58-b8db-798e55ff80e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/preceding::div[5]</value>
      <webElementGuid>d6c83eca-e460-4595-addb-0b30609b6c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Medium']/parent::*</value>
      <webElementGuid>bcaa089b-465e-474f-9b64-fe199c90dcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]</value>
      <webElementGuid>b7c4ad3a-a198-4720-8607-5aae41e0f451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Medium' or . = 'Medium')]</value>
      <webElementGuid>42224df3-80bb-42b7-92de-7d24f5aed8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
