<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_r1</name>
   <tag></tag>
   <elementGuidId>83d286b5-233a-46c9-9a58-35efb4f7795d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#«r1»</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='«r1»']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>daf2c127-8993-4b90-9cd0-55e7cfa6a608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0840dd71-cac1-4607-b8f6-0bde6102f664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>«r1»</value>
      <webElementGuid>91098a90-721a-4ebe-87f9-c8785266bc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1pk1fka</value>
      <webElementGuid>b16d7db6-c760-4cb8-a1a0-2619eb1e91ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ddc216e1-378d-46a5-80c5-b4fb624bf2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3baa7067-34bb-4b14-9b1d-c65fd1ce0a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;«r1»&quot;)</value>
      <webElementGuid>bb47472f-fb45-4c92-b1f8-2fd1295b875d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='«r1»']</value>
      <webElementGuid>511f9dfb-0ff1-4457-aec8-06348fadbed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[2]/div[2]/div/input</value>
      <webElementGuid>98922a5f-e3de-4ad8-8b0a-ba2b48ea0651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5d969b37-1ffc-4586-90e6-71ca2e9939e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '«r1»' and @type = 'password' and @name = 'password']</value>
      <webElementGuid>f6a8cdcb-668f-4876-9027-43fb63ed4111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
