<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Records_btn btn-save</name>
   <tag></tag>
   <elementGuidId>609463ba-89db-4960-a7f8-e6ad815aa31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='FETCH']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;FETCH&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>105b3cc3-eb61-4b9f-b147-aab08f9c59df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>57402359-569c-4579-8c88-a2e842461a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save</value>
      <webElementGuid>708c5ae5-a4d3-47eb-b0b1-23eaa39dd946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FETCH</value>
      <webElementGuid>f07fcb34-618b-4b02-8306-4da1f9ae633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnSubmitFilter</value>
      <webElementGuid>e4f91a9e-8308-4063-a59f-33fd95fb879c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterModal&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer modal-footer-custom&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 ph-wo-padding-right-0px ph-wo-text-align-center&quot;]/span[2]/input[@class=&quot;btn btn-save&quot;]</value>
      <webElementGuid>ddbd842a-0116-406f-bdc9-e2a0a92235d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='FETCH']</value>
      <webElementGuid>0a816f35-d56a-4643-9f7a-2f385ff69dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterModal']/div/div[3]/div/span[2]/input</value>
      <webElementGuid>474f5f3b-b99c-40b3-a2dc-ff26ec82fa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]/input</value>
      <webElementGuid>91ef1ef1-1d46-4eae-b29b-a88c75ca9797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>317e06c6-1e32-46f7-b2df-8208447bc443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
