<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DayWeekUserUser RoleDesignationSkill_1c4881</name>
   <tag></tag>
   <elementGuidId>42e56537-0682-444f-82fd-a68521351d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_groupBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter_groupBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#filter_groupBy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>52b947a5-8551-41fa-ad61-45c1858313cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupBy</value>
      <webElementGuid>da887d5e-e422-47e9-b325-b52a4c63a34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_groupBy</value>
      <webElementGuid>6393cae9-60f7-4f23-8f30-70032075fb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-combobox ph-wo-width-250px</value>
      <webElementGuid>5903f8c8-4642-4378-87a1-23ad501f6185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>fnToggleTopNUserTRToggleCountLabelDisableCheckbox</value>
      <webElementGuid>1671d1b7-d662-4f8b-8c01-dc64814c3b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DayWeekUserUser RoleDesignationSkill LevelLocationService LineRegionDynamic Attribute 5Dynamic Attribute 13Dynamic Attribute 14Dynamic Attribute 15Tenure RangeWork Type Service LineRegion Of Work Type44</value>
      <webElementGuid>e388048c-bace-488f-adb2-6825da6264ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_groupBy&quot;)</value>
      <webElementGuid>eb881908-6023-41fd-97ec-584ab4296ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter_groupBy']</value>
      <webElementGuid>c8211a22-9646-4afd-a33b-78916e539511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='filterTable']/tbody/tr[12]/td[2]/select</value>
      <webElementGuid>403390f9-5471-4d7a-b891-5a31a427ebc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report By'])[1]/following::select[1]</value>
      <webElementGuid>8a112363-93c3-46f6-a8f6-fa9251409b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average'])[1]/following::select[1]</value>
      <webElementGuid>6ad8183c-08a3-4dc4-bd62-1e4f6cc25e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display User Count'])[1]/preceding::select[1]</value>
      <webElementGuid>7977fd65-7b6f-4061-bc11-2a87bb17f4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display Day Count'])[1]/preceding::select[1]</value>
      <webElementGuid>93f3ae93-c446-4a8d-9dd9-412152675e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/select</value>
      <webElementGuid>af955bb2-74d1-4caf-a922-224bcc7d0796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'groupBy' and @id = 'filter_groupBy' and (text() = 'DayWeekUserUser RoleDesignationSkill LevelLocationService LineRegionDynamic Attribute 5Dynamic Attribute 13Dynamic Attribute 14Dynamic Attribute 15Tenure RangeWork Type Service LineRegion Of Work Type44' or . = 'DayWeekUserUser RoleDesignationSkill LevelLocationService LineRegionDynamic Attribute 5Dynamic Attribute 13Dynamic Attribute 14Dynamic Attribute 15Tenure RangeWork Type Service LineRegion Of Work Type44')]</value>
      <webElementGuid>8074f958-8b57-4557-aa51-94f8057fef18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
