<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are you sure you want to remove this _ad8099</name>
   <tag></tag>
   <elementGuidId>74ffafff-da43-44e2-b456-83d9981f1fa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-save.delete-widget.removeDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Yes'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b5b6336-a249-4cac-b7fb-34931d2adcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67a1a1c5-b882-4edc-b640-ceeb68e0ed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save delete-widget removeDiv</value>
      <webElementGuid>505f8ea0-2f0c-4b45-99cb-ffdd5d885832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>6ee7e379-2ada-4eca-9fc8-7b07e55ca25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>NTopCategoriesGroupReport</value>
      <webElementGuid>6880f8dc-7ba2-4ca6-9a1d-330650ada4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>G_TOP_CAT_GROUP_REP</value>
      <webElementGuid>6db18d97-22e7-4498-baab-429a01b749be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeWidget-container_1&quot;)/div[@class=&quot;row user-attribute-buttons&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-6 col-xs-12 fullButton secondButton&quot;]/span[@class=&quot;submit-user-attribute deleteWidget&quot;]/input[@class=&quot;btn btn-save delete-widget removeDiv&quot;]</value>
      <webElementGuid>bb051e2d-029b-4a0d-9c5f-bb8a9b3b3282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Yes'])[2]</value>
      <webElementGuid>1d84697b-7e22-4fca-ba19-f1738e5b2b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='closeWidget-container_1']/div[2]/div[2]/span/input</value>
      <webElementGuid>529d4129-2d80-4ab6-abf0-c502fad65288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>497a5d78-65b1-4543-ba23-499cc78543fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>717d84af-db3b-46c8-9936-14245a1bb3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
