<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Top Categories Activity Type For  CS L_e574cf</name>
   <tag></tag>
   <elementGuidId>f28a076d-65a4-416b-80a6-c6413d189af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeWidget-toggle-container_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='closeWidget-toggle-container_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#closeWidget-toggle-container_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2efc9658-22ea-496e-ae4e-0650b36711cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-tools tool-time dropdown-toggle closeWidget-toggle-container_1</value>
      <webElementGuid>dad42047-9f00-4731-9781-acb37447945d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>adc0056c-d262-46fd-881e-d649b6ee9567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeWidget-toggle-container_1</value>
      <webElementGuid>d9ab008b-9f1d-4cfd-b092-ab271f6a8e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>bc1fba5c-9c5b-4178-998e-4483225dbbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeWidget-toggle-container_1&quot;)</value>
      <webElementGuid>2eb314ff-3d2c-45f5-95b5-5bd3e17283f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='closeWidget-toggle-container_1']</value>
      <webElementGuid>72852c7b-a916-4041-be59-3e9394c51e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetId_container_1']/div/div[2]/div[2]/span</value>
      <webElementGuid>a48811ed-a577-4f14-9ada-0cfde19677f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>47578a0b-3c6a-423b-8c4a-de7684ac76d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Remove' and @id = 'closeWidget-toggle-container_1']</value>
      <webElementGuid>c69af8fe-9f52-4c7d-9c74-c4215d475faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
