<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Captcha Text_loginSubmitFrm</name>
   <tag></tag>
   <elementGuidId>1e800f8b-889a-4df3-8544-e98de3857960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginSubmitFrm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginSubmitFrm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loginSubmitFrm</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7beaf205-8bbc-4ed1-96a6-6cf6733000c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-submit submitloginform</value>
      <webElementGuid>5b37f038-78f1-4c27-9a7e-bbf2394d60bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginSubmitFrm</value>
      <webElementGuid>5fd3ce7c-daf1-4b99-b858-8a5cf3f858b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginSubmitFrm&quot;)</value>
      <webElementGuid>d128d845-a4a9-4eeb-a8b5-29970fe5d051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loginSubmitFrm']</value>
      <webElementGuid>f5fe575e-bee6-4512-971c-b7a241cc2583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AuthenticationForm']/div[2]</value>
      <webElementGuid>86206561-30cd-44b7-ba89-4f0449dc562f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captcha Text'])[1]/following::div[3]</value>
      <webElementGuid>753cd2bd-f05f-43e0-bbf3-2acbd559100a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Id'])[1]/following::div[6]</value>
      <webElementGuid>ae257a4e-4ef7-4aed-a74a-78b847cce3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© JaMocha Tech Pvt. Ltd. 2009-2026'])[1]/preceding::div[5]</value>
      <webElementGuid>a33ca64e-6582-4e26-8c09-b6d8e64a023b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProHance v9.9.10.153'])[1]/preceding::div[6]</value>
      <webElementGuid>2f7b77cd-a0cc-4f64-9473-df02fedaaf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>2e7c997a-0a75-4a77-a69c-f7eebd5ae3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loginSubmitFrm']</value>
      <webElementGuid>6d8badbe-3413-41e5-89c2-806e567ff271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
