<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>a15f5624-5ac5-4063-a9ec-5685c78bb94c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.css-dev-only-do-not-override-os2fvf.ant-btn-primary.ant-btn-color-primary.ant-btn-variant-solid.ant-btn-sm > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='«r35»']/div/div/div[2]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25e33706-8c03-40fb-9376-c17bdbff30c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>2eed6d5c-0764-407d-8e69-9425a798bd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;«r35»&quot;)/div[@class=&quot;ant-popover-inner-content&quot;]/div[@class=&quot;ant-popconfirm-inner-content&quot;]/div[@class=&quot;ant-popconfirm-buttons&quot;]/button[@class=&quot;ant-btn css-dev-only-do-not-override-os2fvf ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-sm&quot;]/span[1]</value>
      <webElementGuid>9f5baee4-e044-4cbc-bde4-f593c09355fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='«r35»']/div/div/div[2]/button[2]/span</value>
      <webElementGuid>f6d78359-7f46-4605-a270-ff4da51204ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::span[1]</value>
      <webElementGuid>ef20b39b-2d82-412e-b4f1-e16ddb50e48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete this event?'])[1]/following::span[2]</value>
      <webElementGuid>5185d05c-7c57-418b-ae1c-d80844525f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>117d438a-9238-41a8-99b1-bc7defa959cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>dc2aa223-64e0-4b06-9531-1ce3d51d25be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>4a444a73-1c38-4bce-915d-999dc5fcd4be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
