<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ADMIN_fa fa-chevron-right icon-white</name>
   <tag></tag>
   <elementGuidId>6b3781c5-942e-423c-b726-ea3fd3e9ce4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='arrow-top']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-chevron-right.icon-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#arrow-top i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>09c55e50-c2a7-4efe-bf73-5feea78239e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-right icon-white</value>
      <webElementGuid>5e76f981-6b35-4e4f-9b26-de37fc619a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrow-top&quot;)/i[@class=&quot;fa fa-chevron-right icon-white&quot;]</value>
      <webElementGuid>1aad0f1f-4e18-44c2-a8a4-c4302b7afaa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='arrow-top']/i</value>
      <webElementGuid>f5305107-733f-4d58-bd55-972d582979cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/i</value>
      <webElementGuid>61a8c888-7878-46a2-9025-ca279be5d02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
