<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shiftName</name>
   <tag></tag>
   <elementGuidId>389f033f-bd85-44ff-834d-e1525110013e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shiftName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shiftName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#shiftName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6261e6f-0996-4ad3-8835-be77f74b453d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shiftName</value>
      <webElementGuid>d4ba5ade-9d07-47ea-8e24-a87fa53befdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shiftName</value>
      <webElementGuid>7eded2c6-ca52-42b6-badf-a464765ba5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a95d9754-64df-47c0-89e0-4550b7754dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65edc0c9-c581-4145-89db-4c015fa9cae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>af728d7b-dc8f-4f71-b635-c377005adca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shiftName&quot;)</value>
      <webElementGuid>a895ac07-c863-48a2-bf7e-d85225881475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WT-Org_WorkShiftPage/Page_ProHance/Page_ProHance/iframe_Hierarchy Mapping_contentFrame</value>
      <webElementGuid>fe904a04-2a61-440b-8f8c-4ad2f44c76fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shiftName']</value>
      <webElementGuid>b5b0dbc8-7c12-4451-8433-7790c6bbdfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='basics']/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>bf2d0e59-ad24-43a2-8d2b-ea525319db2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>da0758a8-840b-49bb-af76-58c0a0267f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'shiftName' and @name = 'shiftName' and @type = 'text']</value>
      <webElementGuid>be87257f-3eb5-4e25-9201-26b6f72753e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
