<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Top Categories Activity Type For  CS L_def09f</name>
   <tag></tag>
   <elementGuidId>78a9631c-a0d6-4943-ba43-7103a925e3ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drilldown-container_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='drilldown-container_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drilldown-container_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca884e39-f484-4062-b6d3-49ac5f5d1973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>cec79e72-1478-474b-96d9-e8af7e941272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drilldown-container_1</value>
      <webElementGuid>de251aef-f172-4264-8131-75f8afa1d737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-tools tool-detail drilldown-container_1 showDrillDown</value>
      <webElementGuid>109af8e1-2cf5-4739-8da0-b09afa47baa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-divid</name>
      <type>Main</type>
      <value>container_1</value>
      <webElementGuid>9af8e95b-4160-4075-b55c-c6da5b364f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>NTopCategoriesDetailsReport</value>
      <webElementGuid>a925db62-528a-43c7-8915-0222027b7e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>G_TOP_CAT_GROUP_REP</value>
      <webElementGuid>523ad054-4254-4f41-92b4-4d021e9b1c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param3</name>
      <type>Main</type>
      <value>container_1</value>
      <webElementGuid>b1cd2595-6f55-4a8c-985b-145b2cae75b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param4</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5f0e377c-b83b-4bca-beaa-4a1f43edcf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param5</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>23456f6a-0b0c-4781-a3fa-b886a3ec2696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drilldown-container_1&quot;)</value>
      <webElementGuid>f272f64c-059d-40e1-9795-a6f1a3eeaa29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='drilldown-container_1']</value>
      <webElementGuid>f4dfa59c-e179-4fd1-9ebf-be9fec29b874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetId_container_1']/div/div[2]/span[2]</value>
      <webElementGuid>58ebfc9d-7986-4596-95c6-af25a9c7ea48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[2]/span[2]</value>
      <webElementGuid>e0d39496-7ecb-4d38-89f9-0c9fb59ce6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'View Details' and @id = 'drilldown-container_1']</value>
      <webElementGuid>6124fcc8-b729-4b68-af74-f497402aebff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
