<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retain container specific period_btn _26f434</name>
   <tag></tag>
   <elementGuidId>bc0d582d-84d4-4ff8-84ec-d64fd59ccf3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-dialog.ph-wf-width-430px-top-30px > div.modal-content > div.modal-footer.modal-footer-custom > div.col-lg-12.col-md-12.col-sm-12.ph-wf-text-align-center.ph-wf-padding-right-0px > span:nth-of-type(2) > input.btn.btn-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SAVE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SAVE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9160add7-96e4-4e0e-b2ef-079c5ec098ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5316c581-891f-457b-8351-5a25546a071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save</value>
      <webElementGuid>c377326a-7bd5-4fbc-b7ff-792e1f1cc382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>192bbd04-1988-4737-b84b-0c10eed751dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnSaveContainerPrefOnClick</value>
      <webElementGuid>7cfa8954-ee29-43c1-8ae2-0c2e9d11657c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabCreationModal&quot;)/div[@class=&quot;modal-dialog ph-wf-width-430px-top-30px&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer modal-footer-custom&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 ph-wf-text-align-center ph-wf-padding-right-0px&quot;]/span[2]/input[@class=&quot;btn btn-save&quot;]</value>
      <webElementGuid>182119c6-46a0-42ea-b32d-23eeb128bdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WF_AddContainer_page/Page_ProHance Workflow/iframe_Workflow Settings_contentFrame</value>
      <webElementGuid>1745e47e-462d-4040-b763-2843dc9f2d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SAVE']</value>
      <webElementGuid>156ca79a-87d2-4023-92a9-7553cf6c93c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabCreationModal']/div/div/div[5]/div/span[2]/input</value>
      <webElementGuid>c0ee7a93-3a03-41d2-8b28-3f38302191ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span[2]/input</value>
      <webElementGuid>32da6bb9-c7e4-48e6-a48a-8901c004771f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>c27c7cd3-4982-4470-999f-630feeefc400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
