<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PH Services (Tech Team)</name>
   <tag></tag>
   <elementGuidId>a084662c-95bd-494c-b417-1beebbe98c08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#row-1 > #cell-2-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cell-2-undefined'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14faae22-4d09-4442-9ad0-a2e9cc4578ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-2-undefined</value>
      <webElementGuid>a8cd8091-ba19-41d4-90f2-95993a5edbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0a8ccea4-8021-439e-bbb4-c6c82b209ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>a7255ad1-adeb-45da-94f9-10f4abe60319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ggWZvA sc-dTvVRJ sc-jwTyAe kitFYk foMPZz iOgaEC rdt_TableCell</value>
      <webElementGuid>f8020163-20f8-4ff4-829d-fe8530047f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>9b764b8d-dac3-4877-95e4-9604c77f1d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>23%</value>
      <webElementGuid>03bb193a-2c3e-4cf3-aec8-8fbcf5d5b286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PH Services (Tech Team)</value>
      <webElementGuid>80144cd5-35f4-451a-a193-aa2be3582cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-1&quot;)/div[@id=&quot;cell-2-undefined&quot;]</value>
      <webElementGuid>b0278389-21d0-4178-888d-4eb7c83df4a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='cell-2-undefined'])[2]</value>
      <webElementGuid>03ec5040-8d41-41ef-90cf-c014a8611159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-1']/div[2]</value>
      <webElementGuid>52dd629a-efc7-40c8-b105-779ed3d36c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::div[6]</value>
      <webElementGuid>d74e6e4e-7a7b-4aab-b2a0-3c0888877e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DI'])[1]/following::div[8]</value>
      <webElementGuid>b7b4a588-6fd6-4017-91e5-7e48ad8e84a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHTECH'])[1]/preceding::div[2]</value>
      <webElementGuid>b4930d6f-f3fe-47cd-9138-e081401b2f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>87edfe68-2681-4aa7-8e2a-82a2c26c2b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-2-undefined' and (text() = 'PH Services (Tech Team)' or . = 'PH Services (Tech Team)')]</value>
      <webElementGuid>d61d9476-cc54-49ad-b5ec-4e60ad12c4e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
