<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Infra Team</name>
   <tag></tag>
   <elementGuidId>e894882d-5958-44aa-9803-97c76e65679c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.sorting_1 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='CommonDataTableId']/tbody/tr/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Infra Team&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb40d869-584e-41e5-ae9f-a9b14aad2cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>claas</name>
      <type>Main</type>
      <value>wordBreak</value>
      <webElementGuid>6e6e1193-4480-43b2-8c5a-f2650fbef3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Infra Team</value>
      <webElementGuid>eb772aab-0b9e-473b-b456-0d7c0dd6ea6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CommonDataTableId&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/div[1]</value>
      <webElementGuid>e302ad04-ea4f-4895-b0ac-18439f3c7fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WorkTemplateExcel_Page/Page_ProHance/iframe_Hierarchy Mapping_contentFrame</value>
      <webElementGuid>a8e007be-3a40-4ac5-b874-e37fe7d31c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='CommonDataTableId']/tbody/tr/td[2]/div</value>
      <webElementGuid>387ff0cf-60e3-4d7e-b725-6c98e63c977e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#Teams'])[2]/following::div[1]</value>
      <webElementGuid>8608814b-a9f9-4ca5-83e4-e10b4814891f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Days'])[2]/following::div[2]</value>
      <webElementGuid>379b7e0c-6bcf-4422-b508-b76550076659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infra Work Template'])[1]/preceding::div[1]</value>
      <webElementGuid>5e5514a8-e2a4-4088-bd7d-24330e01d0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon, Tue, Wed, Thu, Fri'])[1]/preceding::div[2]</value>
      <webElementGuid>bab50fbf-2549-47a9-8ed6-5b4e6ba785b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Infra Team']/parent::*</value>
      <webElementGuid>ca85bff6-23d2-45c8-a72f-2d614b4e28cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/div</value>
      <webElementGuid>df0af45b-9f10-434f-b882-db2668e34a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Infra Team' or . = 'Infra Team')]</value>
      <webElementGuid>52d7f341-46e4-40a5-aeb8-04904eed1940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
