<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Hierarchy Mapping_contentFrame</name>
   <tag></tag>
   <elementGuidId>f59bf515-a7d6-4da1-bf80-bfb4a4a076c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7f0779dd-1900-4c34-b4d4-d5c7f76e35c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>9303b211-5225-42e5-a78a-497a136aa99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>e8e7e623-b12d-442f-a4cb-aa3c51c13e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6bdd7f45-28af-400d-9d4f-bc392ba6782f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prohance/WorkTemplateSummary.htm?menuItemId=118</value>
      <webElementGuid>313b6c53-30dc-4936-8aab-0edcbbdeecd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFrame&quot;)</value>
      <webElementGuid>3d34d2de-b7c2-4469-8bdf-0c736cf54b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentFrame']</value>
      <webElementGuid>f17c08af-aea4-41dc-8cee-a7c395ac21da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContentDiv']/iframe</value>
      <webElementGuid>eb972ea5-77a1-4fad-9420-1de7b08cdfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>99a93adf-1c03-4bf7-b87b-fedb7c7a2873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame' and @name = 'contentFrame' and @src = '/prohance/WorkTemplateSummary.htm?menuItemId=118']</value>
      <webElementGuid>01d1ead2-0ae2-4c97-a414-fc911985caf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
