<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Infra Team</name>
   <tag></tag>
   <elementGuidId>f1c2f2c6-fd07-4c6f-a706-6989ab6bee78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.sorting_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='CommonDataTableId']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Infra Team&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>41fb21f4-8dea-4b5e-aff3-880785ba420b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>1a19bf29-9fd6-4683-940d-64ae48029a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Infra Team</value>
      <webElementGuid>cf91c6ad-ee67-4e9c-99a0-9049894b715e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CommonDataTableId&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>226c4130-f85d-4080-b28d-b5132cbffc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WorkTemplateExcel_Page/Page_ProHance/iframe_Hierarchy Mapping_contentFrame</value>
      <webElementGuid>490b3c81-d534-4ee0-a5f5-22cb5682aa0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='CommonDataTableId']/tbody/tr/td[2]</value>
      <webElementGuid>c153aae7-8873-4fff-a1bf-cf899cee466a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#Teams'])[2]/following::td[2]</value>
      <webElementGuid>dd526ed1-6e37-48a7-99b8-ba22eb376fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Days'])[2]/following::td[2]</value>
      <webElementGuid>be0cc58b-1cb1-4778-bfd7-c09da8deb46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infra Work Template'])[1]/preceding::td[1]</value>
      <webElementGuid>b6d66ac5-a980-4c84-a757-3fd539f16bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>4bb1ec57-2d3d-4f37-891a-8bde97021796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Infra Team' or . = 'Infra Team')]</value>
      <webElementGuid>d2d4e58f-32cf-4211-8ce5-724c2ae059cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
